"""Namespace-aware CWMP SOAP codec with bounded, safe XML parsing."""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from xml.etree import ElementTree as ET

from src.config import DEFAULT_MAX_SOAP_BYTES

SOAP_ENV = "http://schemas.xmlsoap.org/soap/envelope/"
SOAP_ENC = "http://schemas.xmlsoap.org/soap/encoding/"
XSD = "http://www.w3.org/2001/XMLSchema"
XSI = "http://www.w3.org/2001/XMLSchema-instance"
DEFAULT_CWMP = "urn:dslforum-org:cwmp-1-0"

ET.register_namespace("soap-env", SOAP_ENV)
ET.register_namespace("soap-enc", SOAP_ENC)
ET.register_namespace("xsi", XSI)


class SoapProtocolError(ValueError):
    """Raised when a SOAP message or RPC payload is malformed."""


def _local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


class SoapBuilder:
    def __init__(self, cwmp_namespace: str = DEFAULT_CWMP):
        self.cwmp_namespace = cwmp_namespace

    def _cwmp(self, name: str) -> str:
        return f"{{{self.cwmp_namespace}}}{name}"

    @staticmethod
    def _child(parent: ET.Element, name: str, value: object | None = None) -> ET.Element:
        child = ET.SubElement(parent, name)
        if value is not None:
            child.text = str(value)
        return child

    @staticmethod
    def _serialize(element: ET.Element) -> str:
        return ET.tostring(element, encoding="unicode", short_empty_elements=True)

    def soapify(self, method_body: str | ET.Element | None, id: str | int = 1) -> str:
        envelope = ET.Element(
            f"{{{SOAP_ENV}}}Envelope",
            {"xmlns:xsd": XSD, "xmlns:cwmp": self.cwmp_namespace},
        )
        header = ET.SubElement(envelope, f"{{{SOAP_ENV}}}Header")
        cwmp_id = ET.SubElement(
            header,
            self._cwmp("ID"),
            {f"{{{SOAP_ENV}}}mustUnderstand": "1"},
        )
        cwmp_id.text = str(id)
        body = ET.SubElement(envelope, f"{{{SOAP_ENV}}}Body")

        if isinstance(method_body, ET.Element):
            body.append(method_body)
        elif method_body and method_body.strip():
            try:
                body.append(ET.fromstring(method_body))
            except ET.ParseError as exc:
                raise SoapProtocolError("invalid SOAP body generated by RPC builder") from exc

        xml = ET.tostring(envelope, encoding="utf-8", xml_declaration=True)
        return xml.decode("utf-8")

    def request_set_parameter_values(
        self,
        params: list[Mapping[str, object]],
        param_key: str = "",
    ) -> str:
        if not isinstance(params, list) or not params:
            raise SoapProtocolError("SetParameterValues requires a non-empty parameter list")

        method = ET.Element(self._cwmp("SetParameterValues"))
        parameter_list = ET.SubElement(
            method,
            "ParameterList",
            {f"{{{SOAP_ENC}}}arrayType": f"cwmp:ParameterValueStruct[{len(params)}]"},
        )
        for raw_parameter in params:
            if not isinstance(raw_parameter, Mapping):
                raise SoapProtocolError("each SetParameterValues item must be an object")
            name = raw_parameter.get("Name", raw_parameter.get("name"))
            value = raw_parameter.get("Value", raw_parameter.get("value"))
            value_type = raw_parameter.get("Type", raw_parameter.get("type", "xsd:string"))
            if not isinstance(name, str) or not name.strip():
                raise SoapProtocolError("each SetParameterValues item requires Name")

            item = ET.SubElement(parameter_list, "ParameterValueStruct")
            self._child(item, "Name", name)
            value_element = self._child(item, "Value", "" if value is None else value)
            value_element.set(f"{{{XSI}}}type", str(value_type))

        self._child(method, "ParameterKey", param_key)
        return self._serialize(method)

    def request_get_parameter_values(self, params: list[str]) -> str:
        if not isinstance(params, list) or not params or not all(isinstance(item, str) and item for item in params):
            raise SoapProtocolError("GetParameterValues requires a non-empty list of names")
        method = ET.Element(self._cwmp("GetParameterValues"))
        parameter_names = ET.SubElement(
            method,
            "ParameterNames",
            {f"{{{SOAP_ENC}}}arrayType": f"xsd:string[{len(params)}]"},
        )
        for parameter in params:
            self._child(parameter_names, "string", parameter)
        return self._serialize(method)

    def request_get_parameter_names(self, path_name: str, level: int | bool = 0) -> str:
        if not isinstance(path_name, str):
            raise SoapProtocolError("GetParameterNames requires a parameter path")
        method = ET.Element(self._cwmp("GetParameterNames"))
        self._child(method, "ParameterPath", path_name)
        self._child(method, "NextLevel", "1" if bool(level) else "0")
        return self._serialize(method)

    def request_get_rpc_methods(self) -> str:
        return self._serialize(ET.Element(self._cwmp("GetRPCMethods")))

    def request_reboot(self, key: str = "") -> str:
        method = ET.Element(self._cwmp("Reboot"))
        self._child(method, "CommandKey", key)
        return self._serialize(method)

    def request_reset(self) -> str:
        return self._serialize(ET.Element(self._cwmp("FactoryReset")))

    def response_inform(self, max_envelops: str | int = "1") -> str:
        response = ET.Element(self._cwmp("InformResponse"))
        self._child(response, "MaxEnvelopes", max_envelops)
        return self._serialize(response)

    def response_get_rpc_methods(self, methods: Iterable[str]) -> str:
        method_names = list(methods)
        response = ET.Element(self._cwmp("GetRPCMethodsResponse"))
        method_list = ET.SubElement(
            response,
            "MethodList",
            {f"{{{SOAP_ENC}}}arrayType": f"xsd:string[{len(method_names)}]"},
        )
        for method_name in method_names:
            self._child(method_list, "string", method_name)
        return self._serialize(response)

    def response_transfer_complete(self) -> str:
        return self._serialize(ET.Element(self._cwmp("TransferCompleteResponse")))

    def fault_response(self, faults: Mapping[int, list[str]], fault_code: int) -> str:
        fault_entry = faults.get(fault_code)
        fault_string = fault_entry[0] if fault_entry else "Unknown Error"
        response = ET.Element(f"{{{SOAP_ENV}}}Fault")
        self._child(response, "faultcode", "Server")
        self._child(response, "faultstring", "CWMP fault")
        detail = ET.SubElement(response, "detail")
        cwmp_fault = ET.SubElement(detail, self._cwmp("Fault"))
        self._child(cwmp_fault, "FaultCode", fault_code)
        self._child(cwmp_fault, "FaultString", fault_string)
        return self._serialize(response)


class SoapParser(SoapBuilder):
    def __init__(self, message: bytes | str | None, max_xml_bytes: int = DEFAULT_MAX_SOAP_BYTES):
        raw = message.encode("utf-8") if isinstance(message, str) else (message or b"")
        if len(raw) > max_xml_bytes:
            raise SoapProtocolError("SOAP document exceeds the configured size limit")
        upper = raw.upper()
        if b"<!DOCTYPE" in upper or b"<!ENTITY" in upper:
            raise SoapProtocolError("DTD and entity declarations are not allowed")

        self.root: ET.Element | None = None
        self._body: ET.Element | None = None
        if raw.strip():
            try:
                self.root = ET.fromstring(raw)
            except ET.ParseError as exc:
                raise SoapProtocolError("malformed XML") from exc
            if _local_name(self.root.tag) != "Envelope" or not self.root.tag.startswith(f"{{{SOAP_ENV}}}"):
                raise SoapProtocolError("expected a SOAP 1.1 Envelope")
            self._body = next((item for item in self.root if _local_name(item.tag) == "Body"), None)
            if self._body is None:
                raise SoapProtocolError("SOAP Envelope has no Body")

        cwmp_namespace = DEFAULT_CWMP
        body = self.parse_body()
        if body is not None and body.tag.startswith("{"):
            candidate = body.tag[1:].split("}", 1)[0]
            if candidate.startswith("urn:dslforum-org:cwmp-"):
                cwmp_namespace = candidate
        super().__init__(cwmp_namespace)

    def _find_first(self, local_name: str, root: ET.Element | None = None) -> ET.Element | None:
        source = root if root is not None else self.root
        if source is None:
            return None
        return next((element for element in source.iter() if _local_name(element.tag) == local_name), None)

    def _text(self, local_name: str) -> str | None:
        element = self._find_first(local_name)
        if element is None or element.text is None:
            return None
        return element.text.strip()

    def parse_body(self) -> ET.Element | None:
        if self._body is None:
            return None
        return next(iter(self._body), None)

    def parse_type_request(self) -> str | None:
        body = self.parse_body()
        return _local_name(body.tag) if body is not None else None

    def parse_cwmp_id(self) -> str | None:
        return self._text("ID")

    def parse_events(self) -> list[str]:
        if self.root is None:
            return []
        events: list[str] = []
        for event_struct in (item for item in self.root.iter() if _local_name(item.tag) == "EventStruct"):
            event_code = self._find_first("EventCode", event_struct)
            if event_code is not None and event_code.text:
                events.append(event_code.text.strip())
        return events

    def parse_parameters(self) -> list[dict[str, str]]:
        if self.root is None:
            return []
        parameters: list[dict[str, str]] = []
        for struct in (item for item in self.root.iter() if _local_name(item.tag) == "ParameterValueStruct"):
            name = self._find_first("Name", struct)
            value = self._find_first("Value", struct)
            if name is None or not name.text or value is None:
                continue
            value_type = value.attrib.get(f"{{{XSI}}}type", value.attrib.get("type", "xsd:string"))
            parameters.append(
                {
                    "Name": name.text.strip(),
                    "Value": value.text or "",
                    "Type": value_type,
                }
            )
        return parameters

    def parse_manufacturer(self) -> str | None:
        return self._text("Manufacturer")

    def parse_oui(self) -> str | None:
        return self._text("OUI")

    def parse_product_class(self) -> str | None:
        return self._text("ProductClass")

    def parse_serial_number(self) -> str | None:
        return self._text("SerialNumber")

    def parse_current_time(self) -> str | None:
        return self._text("CurrentTime")

    def parse_retry_count(self) -> str | None:
        return self._text("RetryCount")

    def parse_max_envelopes(self) -> str | None:
        return self._text("MaxEnvelopes")

    def parse_status(self) -> str | None:
        return self._text("Status")

    def parse_faults(self) -> dict[int, list[str]]:
        body = self.parse_body()
        if body is None or _local_name(body.tag) != "Fault":
            return {}
        codes = [item for item in body.iter() if _local_name(item.tag) == "FaultCode"]
        strings = [item for item in body.iter() if _local_name(item.tag) == "FaultString"]
        faults: dict[int, list[str]] = {}
        for code, description in zip(codes, strings, strict=False):
            try:
                faults[int((code.text or "").strip())] = [(description.text or "").strip()]
            except ValueError:
                continue
        return faults
